export interface Engineer {
  nik: string
  nama_eos: string
  no_hp: string
  cc_area: string
  nama_cc: string
  lokasi_site: string
}

export const engineerData: Engineer[] = [
  {
    nik: "175984",
    nama_eos: "WAHYU EKO FEBRIANTO",
    no_hp: "0812-16615400",
    cc_area: "AREA",
    nama_cc: "AMCOR TOBACCO PACKAGING INDONESIA PT",
    lokasi_site: "PASURUAN",
  },
  {
    nik: "175944",
    nama_eos: "EDY PURWANTO",
    no_hp: "0812-89891352",
    cc_area: "AREA",
    nama_cc: "AMRITA GRIYATAMA",
    lokasi_site: "JAKARTA TIMUR",
  },
  {
    nik: "175968",
    nama_eos: "RONNY PERMANA",
    no_hp: "0821-28117766",
    cc_area: "AREA",
    nama_cc: "AMMEERRAA HOTEL",
    lokasi_site: "BANDUNG",
  },
  {
    nik: "175966",
    nama_eos: "ARRY MUHAMMAD SADIKIN",
    no_hp: "0813-95104210",
    cc_area: "AREA",
    nama_cc: "ANACLAIR u/ DAVID SANTOSO SE",
    lokasi_site: "BANDUNG",
  },
  {
    nik: "176785",
    nama_eos: "SIGIT DWIYANTORO",
    no_hp: "0851-5747-5500",
    cc_area: "AREA",
    nama_cc: "ANAK ELANG MOTORINDO PT",
    lokasi_site: "JAKARTA UTARA",
  },
  {
    nik: "175942",
    nama_eos: "BORIS SIMEON",
    no_hp: "0812-80128139",
    cc_area: "AREA",
    nama_cc: "ANDALAN FINANCE INDONESIA PT",
    lokasi_site: "JAKARTA TIMUR",
  },
  {
    nik: "156368",
    nama_eos: "APRIYANTO SUMARNA",
    no_hp: "0812-98608590",
    cc_area: "CC",
    nama_cc: "ANEKA TAMBANG PT",
    lokasi_site: "JAKARTA PUSAT",
  },
  {
    nik: "59387",
    nama_eos: "AHMAD FARIDUDDIN",
    no_hp: "0812-89819375",
    cc_area: "CC",
    nama_cc: "ANGGADA PUTRA REKSO MULIA (REKSO HOLDING)",
    lokasi_site: "JAKARTA PUSAT",
  },
  {
    nik: "176785",
    nama_eos: "SIGIT DWIYANTORO",
    no_hp: "0851-5747-5500",
    cc_area: "AREA",
    nama_cc: "ANGGUN ZAMBRUT KHATULISTIWA PT",
    lokasi_site: "JAKARTA UTARA",
  },
  {
    nik: "75564",
    nama_eos: "MOHAMMAD SAIFULLOH MASLUKI",
    no_hp: "0821-40704645",
    cc_area: "AREA",
    nama_cc: "ANGKASA PURA I u/ BANDARA JUANDA",
    lokasi_site: "SURABAYA UTARA",
  },
  {
    nik: "200619",
    nama_eos: "AHMAD SYAIFUL ANAM",
    no_hp: "0851-5517-3555",
    cc_area: "CC",
    nama_cc: "ANGKASA PURA SARANA DIGITAL",
    lokasi_site: "TANGERANG",
  },
  {
    nik: "161329",
    nama_eos: "BUDIMAN JAFFERSON SIMARMATA",
    no_hp: "0813-8338-1874",
    cc_area: "CC",
    nama_cc: "ANGKASA PURA SARANA DIGITAL",
    lokasi_site: "TANGERANG",
  },
  {
    nik: "75555",
    nama_eos: "DEKO PRAMIJAYA",
    no_hp: "0813-68198819",
    cc_area: "CC",
    nama_cc: "ANGKASA PURA SARANA DIGITAL",
    lokasi_site: "TANGERANG",
  },
  {
    nik: "193439",
    nama_eos: "EKO BUDIYANTO",
    no_hp: "0852-12231238",
    cc_area: "CC",
    nama_cc: "ANGKASA PURA SARANA DIGITAL",
    lokasi_site: "TANGERANG",
  },
  {
    nik: "87152",
    nama_eos: "ILMAN FAJAR",
    no_hp: "0853-20094612",
    cc_area: "CC",
    nama_cc: "ANGKASA PURA SARANA DIGITAL",
    lokasi_site: "TANGERANG",
  },
  {
    nik: "200619",
    nama_eos: "AHMAD SYAIFUL ANAM",
    no_hp: "0851-5517-3555",
    cc_area: "CC",
    nama_cc: "ANGKASAPURA I",
    lokasi_site: "TANGERANG",
  },
  {
    nik: "161329",
    nama_eos: "BUDIMAN JAFFERSON SIMARMATA",
    no_hp: "0813-8338-1874",
    cc_area: "CC",
    nama_cc: "ANGKASAPURA I",
    lokasi_site: "TANGERANG",
  },
  {
    nik: "75555",
    nama_eos: "DEKO PRAMIJAYA",
    no_hp: "0813-68198819",
    cc_area: "CC",
    nama_cc: "ANGKASAPURA I",
    lokasi_site: "TANGERANG",
  },
  {
    nik: "193439",
    nama_eos: "EKO BUDIYANTO",
    no_hp: "0852-12231238",
    cc_area: "CC",
    nama_cc: "ANGKASAPURA I",
    lokasi_site: "TANGERANG",
  },
  {
    nik: "87152",
    nama_eos: "ILMAN FAJAR",
    no_hp: "0853-20094612",
    cc_area: "CC",
    nama_cc: "ANGKASAPURA I",
    lokasi_site: "TANGERANG",
  },
]

